#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Oct 19 13:37:03 EEST 2021
# SW Build 3118627 on Tue Feb  9 05:13:49 MST 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto b5afc52f98804083a00649bb596efad1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot upOrDown_Counter_tb_behav xil_defaultlib.upOrDown_Counter_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto b5afc52f98804083a00649bb596efad1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot upOrDown_Counter_tb_behav xil_defaultlib.upOrDown_Counter_tb xil_defaultlib.glbl -log elaborate.log

