#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Oct 19 13:37:06 EEST 2021
# SW Build 3118627 on Tue Feb  9 05:13:49 MST 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim upOrDown_Counter_tb_behav -key {Behavioral:sim_1:Functional:upOrDown_Counter_tb} -tclbatch upOrDown_Counter_tb.tcl -log simulate.log"
xsim upOrDown_Counter_tb_behav -key {Behavioral:sim_1:Functional:upOrDown_Counter_tb} -tclbatch upOrDown_Counter_tb.tcl -log simulate.log

