webtalk_init -webtalk_dir /home/robert/Facultate/3_anul/Third-Year/1_sem/CN2/1_lab/lab1_2/adder/adder.sim/sim_1/behav/xsim/xsim.dir/upOrDown_Counter_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct 19 13:35:35 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3118627" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b66b6e8e-55e9-4a6e-9365-c52de80c839d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b5afc52f98804083a00649bb596efad1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2187.666 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115308_KB" -context "xsim\\usage"
webtalk_transmit -clientid 293499944 -regid "" -xml /home/robert/Facultate/3_anul/Third-Year/1_sem/CN2/1_lab/lab1_2/adder/adder.sim/sim_1/behav/xsim/xsim.dir/upOrDown_Counter_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/robert/Facultate/3_anul/Third-Year/1_sem/CN2/1_lab/lab1_2/adder/adder.sim/sim_1/behav/xsim/xsim.dir/upOrDown_Counter_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/robert/Facultate/3_anul/Third-Year/1_sem/CN2/1_lab/lab1_2/adder/adder.sim/sim_1/behav/xsim/xsim.dir/upOrDown_Counter_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
